# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/lirei-user/aarch64-base:latest"
  amd64: "ghcr.io/lirei-user/amd64-base:latest"
  armhf: "ghcr.io/lirei-user/armhf-base:latest"
  armv7: "ghcr.io/lirei-user/armv7-base:latest"
  i386: "ghcr.io/lirei-user/i386-base:latest"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Example add-on"
  org.opencontainers.image.description: "Example add-on to use as a blueprint for new add-ons."
  org.opencontainers.image.source: "https://github.com/lirei-user/addons-example"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2021.09.0"
