# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Example add-on
version: "1.2.6"
slug: example
description: POCTES add-on
url: "https://github.com/lirei-user/addons-poctes/tree/main/poctes"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  update: false
  piptoken: ""
  projectid: ""
  aconfig:
    device_id: ""
    realm: ""
    credentials_secret: ""
    pairing_base_url: ""
    persistency_dir: "."
  interface: "{}"
schema:
  update: bool
  piptoken: "str?"
  projectid: "str?"
  aconfig:
    device_id: "str?"
    realm: "str?"
    credentials_secret: "str?"
    pairing_base_url: "str?"
    persistency_dir: "str?"
  interface: "str?"

image: "ghcr.io/lirei-user/{arch}-addon-poctes"
