# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Example add-on
version: "1.2.2"
slug: example
description: POCTES add-on
url: "https://github.com/lirei-user/addons-example/tree/main/poctes"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/lirei-user/{arch}-addon-poctes"
